// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXFwgmgSyh4O4g-WtYApEmd5-KtdQUcE',
    appId: '1:140582184873:web:7179ebb2088e8c86fa06b8',
    messagingSenderId: '140582184873',
    projectId: 'traveljournel-b7592',
    authDomain: 'traveljournel-b7592.firebaseapp.com',
    storageBucket: 'traveljournel-b7592.firebasestorage.app',
    measurementId: 'G-CTQY4NPTDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdSAD6l7SE41WP_Vratb86jApahYHJRk',
    appId: '1:140582184873:android:071a6c4797c601a2fa06b8',
    messagingSenderId: '140582184873',
    projectId: 'traveljournel-b7592',
    storageBucket: 'traveljournel-b7592.firebasestorage.app',
  );

}