name: auth_repo
description: A reusable authentication package for Wanderlog app.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_auth: ^5.5.3
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.0
